export const FEATURES_DATA = [
  {
    icon: "🤖",
    title: "AI-Powered Fitness Plans",
    description:
      "Customized workout routines generated by artificial intelligence based on your body type, fitness level, and goals.",
  },
  {
    icon: "🍏",
    title: "Personalized Nutrition",
    description: "AI-driven meal suggestions and diet tracking that adapt to your dietary preferences and fitness progress.",
  },
  {
    icon: "💬",
    title: "24/7 AI Coach",
    description: "Instant access to an AI fitness coach that provides guidance, motivation, and answers to your fitness-related questions anytime.",
  },
  {
    icon: "📊",
    title: "Progress Analytics",
    description: "Advanced data visualization and progress tracking to monitor your fitness journey and celebrate milestones.",
  },
  {
    icon: "🏃",
    title: "Workout Library",
    description: "Access to a vast library of exercises with video demonstrations and proper form guidance.",
  },
  {
    icon: "🤝",
    title: "Community Support",
    description: "Join a supportive community of like-minded individuals to share progress and stay motivated.",
  },
];
    